apiVersion: v1
kind: Service
metadata:
  labels:
    app: httpd-deploy
  name: httpd-service
spec:
  ports:
  - targetPort: 80
    port: 80
    nodePort: 30008
  selector:
    app: httpd-deploy
  type: NodePort