apiVersion: v1
kind: Service
metadata:
  labels:
    app: nagios-deployment
  name: nagios-service
spec:
  ports:
  - port: 80
    nodeport: 30008
    targetPort: 80
  selector:
    app: nagios-deployment
  type: targetPort