apiVersion: v1
kind: Service
metadata:
  labels:
    app: jenkins
  name: jenkins-service
spec:
  ports:
  - port: 50000
    nodePort: 30008
    targetPort: 50000
  selector:
    app: jenkins
  type: NodePort