apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana-deployment-nautilus
  name: grafana-service
spec:
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 32000
  selector:
    app: grafana-deployment-nautilus
  type: NodePort